"""Adiciona indices para otimizacao de queries

Revision ID: 8fe6e8ca9860
Revises: 
Create Date: 2026-01-05 14:27:50.181908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fe6e8ca9860'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conferencia', schema=None) as batch_op:
        batch_op.alter_column('data_conferencia_finalizada',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_conferencia_conferente_nome'), ['conferente_nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_conferencia_data_conferencia_finalizada'), ['data_conferencia_finalizada'], unique=False)
        batch_op.create_index(batch_op.f('ix_conferencia_data_finalizacao'), ['data_finalizacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_conferencia_data_inicio_conferencia'), ['data_inicio_conferencia'], unique=False)
        batch_op.create_index(batch_op.f('ix_conferencia_nome_fornecedor'), ['nome_fornecedor'], unique=False)
        batch_op.create_index(batch_op.f('ix_conferencia_nome_transportadora'), ['nome_transportadora'], unique=False)
        batch_op.create_index(batch_op.f('ix_conferencia_numero_nota_fiscal'), ['numero_nota_fiscal'], unique=False)
        batch_op.create_index(batch_op.f('ix_conferencia_qtd_volumes'), ['qtd_volumes'], unique=False)
        batch_op.create_index(batch_op.f('ix_conferencia_recebido_por'), ['recebido_por'], unique=False)
        batch_op.create_index(batch_op.f('ix_conferencia_resolvido_contabilidade'), ['resolvido_contabilidade'], unique=False)
        batch_op.create_index(batch_op.f('ix_conferencia_resolvido_gestor'), ['resolvido_gestor'], unique=False)
        batch_op.create_index(batch_op.f('ix_conferencia_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_conferencia_total_itens'), ['total_itens'], unique=False)
        batch_op.create_index(batch_op.f('ix_conferencia_vendedor_nome'), ['vendedor_nome'], unique=False)

    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedido_comprador'), ['comprador'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedido_data_criacao'), ['data_criacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedido_data_finalizacao'), ['data_finalizacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedido_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedido_tipo_req'), ['tipo_req'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedido_vendedor'), ['vendedor'], unique=False)

    with op.batch_alter_table('registro_compra', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registro_compra_comprador_nome'), ['comprador_nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_registro_compra_data_criacao'), ['data_criacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_registro_compra_editor_nome'), ['editor_nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_registro_compra_fornecedor'), ['fornecedor'], unique=False)
        batch_op.create_index(batch_op.f('ix_registro_compra_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registro_compra_observacao'), ['observacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_registro_compra_status'), ['status'], unique=False)

    with op.batch_alter_table('separacao', schema=None) as batch_op:
        batch_op.alter_column('separadores_nomes',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_separacao_data_criacao'), ['data_criacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_separacao_data_finalizacao'), ['data_finalizacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_separacao_numero_movimentacao'), ['numero_movimentacao'], unique=True)
        batch_op.create_index(batch_op.f('ix_separacao_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_separacao_vendedor_nome'), ['vendedor_nome'], unique=False)

    with op.batch_alter_table('sugestao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sugestao_comprador'), ['comprador'], unique=False)
        batch_op.create_index(batch_op.f('ix_sugestao_data_criacao'), ['data_criacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_sugestao_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sugestao_vendedor'), ['vendedor'], unique=False)

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('prioridade_fila')
        batch_op.drop_column('ativo_na_fila')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ativo_na_fila', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('prioridade_fila', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('sugestao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sugestao_vendedor'))
        batch_op.drop_index(batch_op.f('ix_sugestao_status'))
        batch_op.drop_index(batch_op.f('ix_sugestao_data_criacao'))
        batch_op.drop_index(batch_op.f('ix_sugestao_comprador'))

    with op.batch_alter_table('separacao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_separacao_vendedor_nome'))
        batch_op.drop_index(batch_op.f('ix_separacao_status'))
        batch_op.drop_index(batch_op.f('ix_separacao_numero_movimentacao'))
        batch_op.drop_index(batch_op.f('ix_separacao_data_finalizacao'))
        batch_op.drop_index(batch_op.f('ix_separacao_data_criacao'))
        batch_op.alter_column('separadores_nomes',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('registro_compra', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registro_compra_status'))
        batch_op.drop_index(batch_op.f('ix_registro_compra_observacao'))
        batch_op.drop_index(batch_op.f('ix_registro_compra_id'))
        batch_op.drop_index(batch_op.f('ix_registro_compra_fornecedor'))
        batch_op.drop_index(batch_op.f('ix_registro_compra_editor_nome'))
        batch_op.drop_index(batch_op.f('ix_registro_compra_data_criacao'))
        batch_op.drop_index(batch_op.f('ix_registro_compra_comprador_nome'))

    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedido_vendedor'))
        batch_op.drop_index(batch_op.f('ix_pedido_tipo_req'))
        batch_op.drop_index(batch_op.f('ix_pedido_status'))
        batch_op.drop_index(batch_op.f('ix_pedido_data_finalizacao'))
        batch_op.drop_index(batch_op.f('ix_pedido_data_criacao'))
        batch_op.drop_index(batch_op.f('ix_pedido_comprador'))

    with op.batch_alter_table('conferencia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conferencia_vendedor_nome'))
        batch_op.drop_index(batch_op.f('ix_conferencia_total_itens'))
        batch_op.drop_index(batch_op.f('ix_conferencia_status'))
        batch_op.drop_index(batch_op.f('ix_conferencia_resolvido_gestor'))
        batch_op.drop_index(batch_op.f('ix_conferencia_resolvido_contabilidade'))
        batch_op.drop_index(batch_op.f('ix_conferencia_recebido_por'))
        batch_op.drop_index(batch_op.f('ix_conferencia_qtd_volumes'))
        batch_op.drop_index(batch_op.f('ix_conferencia_numero_nota_fiscal'))
        batch_op.drop_index(batch_op.f('ix_conferencia_nome_transportadora'))
        batch_op.drop_index(batch_op.f('ix_conferencia_nome_fornecedor'))
        batch_op.drop_index(batch_op.f('ix_conferencia_data_inicio_conferencia'))
        batch_op.drop_index(batch_op.f('ix_conferencia_data_finalizacao'))
        batch_op.drop_index(batch_op.f('ix_conferencia_data_conferencia_finalizada'))
        batch_op.drop_index(batch_op.f('ix_conferencia_conferente_nome'))
        batch_op.alter_column('data_conferencia_finalizada',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
